from .stock_valuation import StockValuation

class Inventory:
    def __init__(self):
        # ...existing code...
        self.stock_valuation = StockValuation()
        # ...existing code...

    def calculate_initial_inventory(self, product_id, date):
        # ...existing code...
        initial_value = self.stock_valuation.get_initial_value(product_id, date)
        # ...existing code...
        return initial_inventory, initial_value

    def calculate_final_inventory(self, product_id, date):
        # ...existing code...
        final_value = self.stock_valuation.get_final_value(product_id, date)
        # ...existing code...
        return final_inventory, final_value

    def calculate_total_entries(self, product_id, start_date, end_date):
        # ...existing code...
        total_entries_qty, total_entries_value = self.stock_valuation.get_total_entries(product_id, start_date, end_date)
        # ...existing code...
        return total_entries_qty, total_entries_value

    def calculate_total_exits(self, product_id, start_date, end_date):
        # ...existing code...
        total_exits_qty, total_exits_value = self.stock_valuation.get_total_exits(product_id, start_date, end_date)
        # ...existing code...
        return total_exits_qty, total_exits_value
